new tutorial: Migration guide from fastai's python library to FastAI.jl
FluxML/FastAI.jl pull request #21
Opened 2021-03-28 17:39 UTC by War-Eagl

First of three part tutorial on migrating from Fastai's python library to FastAI.jl. This is supposed to beginner level and I've written down things that I felt crucial when I came from the Fastai's python's library.

2021-03-29 20:39 UTC, darsnack commented
I feel like one important part of fast.ai is the [data block API](https://docs.fast.ai/tutorial.datablock). This tutorial would benefit from a mapping from that API to our API (MLDataPattern.jl + DataAugmentation.jl).

2021-03-30 12:49 UTC, darsnack requested changes
Left some comments. Overall, I think this is a good start, but I would prefer to see more of a focus on "translating" concepts instead of code snippets.

2021-03-30 12:49 UTC, darsnack commented on docs/notebooks/Migration_Guide_beginner.ipynb
> +        "Dataloaders are important aspects of fastai's python library. These objects are like assembly lines that feed materials to the machine. Likewise dataloaders feed data to the model. \n",
```suggestion
        "Dataloaders are important aspects of fastai's python library. Like an assembly line feeding materials to the next machine, dataloaders feed data to the model. \n",
```

2021-03-30 12:49 UTC, darsnack commented on docs/notebooks/Migration_Guide_beginner.ipynb
> +    },
My concern with this section is that it blurs the line between data containers and data iterators. For a migration guide, I would prefer to see an explanation of how in FastAI.jl, we have a single interface — `MLDataPattern.getobs` and `MLDataPattern.nobs` — for both data containers and data iterators. The only distinction is that data iterators like `eachbatch` or  `eachobs` also implement the [iteration interface](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration) from Base.

This should be contrasted with fast.ai where there is a distinction between datasets and data loaders.

2021-03-30 12:49 UTC, darsnack commented on docs/notebooks/Migration_Guide_beginner.ipynb
> +        "Learner is the object that binds the data loaders with the model and sets the other hyper parameters like loss function, optimizers, etc. There is `Learner()` function which is similar to fa
```suggestion
        "The learner is the object that binds the data loaders with the model and sets the other hyper parameters like loss function, optimizers, etc. There is `Learner()` function which is similar to fastai's `cnn_learner` function. The below python code can be translated as,\n",
```

2021-03-30 12:49 UTC, darsnack commented on docs/notebooks/Migration_Guide_beginner.ipynb
> +    },
I would just delete this section. The comparison to `Learner` isn't exact, and I think `cnn_learner` is more closely compared to `methodlearner`.

2021-03-30 17:42 UTC, War-Eagl commented
I corrected the typos and deleted those lines in Learner section. I also added some explanation in Dataloaders section. Does that make any sense  and do any justice to the tutorial?

2022-07-06 12:42 UTC, closed without merging