Fix the broken link in the README
FluxML/FastAI.jl pull request #257
Opened 2022-08-18 08:08 UTC by nathanaelbosch

2022-08-18 12:36 UTC, darsnack requested changes
Thanks! I think there is one more place where this happens.

2022-08-18 12:36 UTC, darsnack commented on README.md
>  - finding out [how you can search for and find datasets and other functionality](https://fluxml.ai/FastAI.jl/dev/documents%2Fdocs%2Fdiscovery.md); or
This link probably needs the same fix?

2022-08-18 13:31 UTC, nathanaelbosch commented on README.md
>  - finding out [how you can search for and find datasets and other functionality](https://fluxml.ai/FastAI.jl/dev/documents%2Fdocs%2Fdiscovery.md); or
That link works for me.

2022-09-06 16:12 UTC, darsnack approved these changes

2022-09-06 16:13 UTC, merged